import { Property, Lead, Testimonial, Blog } from "@/types";

export const PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "premium-plot-panvel-sector-12",
    propertyCode: "PLT-PNV-001",
    title: "Premium Plot in Panvel Sector 12",
    status: "available",
    featured: true,
    published: true,
    location: "Panvel",
    village: "Chikhale",
    taluka: "Panvel",
    district: "Raigad",
    coordinates: { lat: 18.9894, lng: 73.1175 },
    priceTotal: 6500000,
    pricePerSqft: 2600,
    areaSqft: 2500,
    areaGuntha: 2.3,
    areaAcre: 0.057,
    zoningType: "Residential",
    titleClarity: "clear",
    roadAccess: true,
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      "https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?w=800",
    ],
    highlights: [
      "15 min from Navi Mumbai Airport",
      "Clear NA title",
      "60 ft wide road access",
      "CIDCO approved zone",
      "Corner plot",
    ],
    nearbyLandmarks: [
      { name: "Navi Mumbai International Airport", distance: "12 km", type: "airport" },
      { name: "Panvel Railway Station", distance: "4 km", type: "railway" },
      { name: "Mumbai-Pune Expressway", distance: "2 km", type: "highway" },
      { name: "City Centre Mall", distance: "3 km", type: "market" },
    ],
    investmentReasoning:
      "With the Navi Mumbai International Airport becoming operational and the Mumbai-Pune Expressway missing link reducing travel time by 25 minutes, Panvel is positioned for exponential growth. Land values in the micro-market have historically appreciated 18-22% annually in infrastructure corridors.",
    whyThisProperty:
      "This corner plot sits in one of Panvel's fastest-growing residential corridors. Clear NA title, excellent road connectivity, and proximity to upcoming commercial development make it an ideal investment for both resale and development.",
    seoTitle: "Premium Residential Plot in Panvel Sector 12 | Plotsify",
    seoDescription:
      "2500 sqft NA plot in Panvel with clear title, road access. Near Navi Mumbai Airport. ₹65 L. Verified by Plotsify.",
    createdAt: "2024-01-15",
    updatedAt: "2024-05-01",
  },
  {
    id: "2",
    slug: "agricultural-land-khalapur-highway",
    propertyCode: "PLT-KHL-001",
    title: "Agricultural Land near Khalapur Highway",
    status: "available",
    featured: true,
    published: true,
    location: "Khalapur",
    village: "Vangani",
    taluka: "Khalapur",
    district: "Raigad",
    coordinates: { lat: 18.8256, lng: 73.3124 },
    priceTotal: 4800000,
    pricePerSqft: 800,
    areaSqft: 6000,
    areaGuntha: 5.5,
    areaAcre: 0.138,
    zoningType: "Agricultural / NA Conversion Possible",
    titleClarity: "clear",
    roadAccess: true,
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800",
      "https://images.unsplash.com/photo-1589519160732-576fc165122f?w=800",
    ],
    highlights: [
      "On Mumbai-Pune Expressway corridor",
      "Huge upside on NA conversion",
      "Clear 7/12 title",
      "Flat, level land",
      "Water source available",
    ],
    nearbyLandmarks: [
      { name: "Mumbai-Pune Expressway", distance: "0.5 km", type: "highway" },
      { name: "Khalapur Toll Plaza", distance: "3 km", type: "highway" },
      { name: "Khopoli Market", distance: "8 km", type: "market" },
      { name: "Aamby Valley City", distance: "15 km", type: "other" },
    ],
    investmentReasoning:
      "The Mumbai-Pune Expressway Missing Link project reduces a critical stretch by nearly 6 km and cuts travel time by 20-25 minutes, dramatically improving Khalapur's accessibility. This corridor is attracting logistics, warehousing, and weekend home developers.",
    whyThisProperty:
      "A rare flat agricultural parcel with easy NA conversion prospects, direct expressway visibility, and clear 7/12 title. Ideal for weekend farmhouse development, eco-resort concept, or long-term investment hold.",
    seoTitle: "Agricultural Land near Khalapur Expressway | Plotsify",
    seoDescription:
      "6000 sqft agricultural land near Khalapur with clear title, expressway access. ₹48 L. Ideal for farmhouse or investment.",
    createdAt: "2024-02-10",
    updatedAt: "2024-04-28",
  },
  {
    id: "3",
    slug: "residential-plot-panvel-airport-road",
    propertyCode: "PLT-PNV-002",
    title: "Residential Plot on Airport Access Road",
    status: "available",
    featured: true,
    published: true,
    location: "Panvel",
    village: "Targhar",
    taluka: "Panvel",
    district: "Raigad",
    coordinates: { lat: 18.9643, lng: 73.0985 },
    priceTotal: 9200000,
    pricePerSqft: 3100,
    areaSqft: 2967,
    areaGuntha: 2.72,
    areaAcre: 0.068,
    zoningType: "Residential / Commercial",
    titleClarity: "clear",
    roadAccess: true,
    gallery: [
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=800",
    ],
    highlights: [
      "Direct airport road visibility",
      "Mixed-use zoning",
      "High commercial potential",
      "Verified CIDCO zone",
      "90 ft road frontage",
    ],
    nearbyLandmarks: [
      { name: "Navi Mumbai International Airport", distance: "6 km", type: "airport" },
      { name: "Atal Setu Access Point", distance: "9 km", type: "highway" },
      { name: "Uran Industrial Area", distance: "5 km", type: "other" },
      { name: "Panvel Bus Terminus", distance: "7 km", type: "other" },
    ],
    investmentReasoning:
      "Positioned directly on the main airport access corridor, this mixed-use plot is set to benefit from both residential demand from airport workers and commercial activity from travellers and businesses. CIDCO's master plan shows this zone earmarked for high-density development.",
    whyThisProperty:
      "Once-in-a-decade opportunity to own land directly on the airport approach road. Mixed-use zoning means maximum flexibility for the buyer, from luxury villas to boutique commercial development.",
    createdAt: "2024-03-01",
    updatedAt: "2024-05-05",
  },
  {
    id: "4",
    slug: "weekend-farmhouse-plot-khalapur-valley",
    propertyCode: "PLT-KHL-002",
    title: "Weekend Farmhouse Plot in Khalapur Valley",
    status: "available",
    featured: false,
    published: true,
    location: "Khalapur",
    village: "Bhoiwadi",
    taluka: "Khalapur",
    district: "Raigad",
    coordinates: { lat: 18.8044, lng: 73.3251 },
    priceTotal: 3200000,
    pricePerSqft: 640,
    areaSqft: 5000,
    areaGuntha: 4.59,
    areaAcre: 0.115,
    zoningType: "Agriculture",
    titleClarity: "clear",
    roadAccess: true,
    gallery: [
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1589519160732-576fc165122f?w=800",
    ],
    highlights: [
      "Scenic valley views",
      "Natural stream nearby",
      "Perfect for eco-resort",
      "Close to Mumbai-Pune Expressway",
      "Quiet, green surroundings",
    ],
    nearbyLandmarks: [
      { name: "Mumbai-Pune Expressway", distance: "4 km", type: "highway" },
      { name: "Imagica Theme Park", distance: "12 km", type: "other" },
      { name: "Khalapur Village", distance: "2 km", type: "market" },
    ],
    investmentReasoning:
      "As Mumbai's urban population seeks green getaways, Khalapur's valley plots are commanding premium weekend home prices. The new expressway missing link makes Mumbai a 60-minute drive, transforming weekend farmhouse economics.",
    whyThisProperty:
      "Lush valley setting with natural stream access and expansive views. Ideal for a private farmhouse, yoga retreat, or boutique eco-stay. Immediate possession available.",
    createdAt: "2024-01-20",
    updatedAt: "2024-04-15",
  },
  {
    id: "5",
    slug: "large-land-parcel-panvel-industrial",
    propertyCode: "PLT-PNV-003",
    title: "Large Land Parcel near Panvel Industrial Zone",
    status: "reserved",
    featured: false,
    published: true,
    location: "Panvel",
    village: "Kalundre",
    taluka: "Panvel",
    district: "Raigad",
    coordinates: { lat: 18.9712, lng: 73.1032 },
    priceTotal: 18000000,
    pricePerSqft: 1500,
    areaSqft: 12000,
    areaGuntha: 11.01,
    areaAcre: 0.275,
    zoningType: "Industrial / Commercial",
    titleClarity: "clear",
    roadAccess: true,
    gallery: [
      "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    ],
    highlights: [
      "12,000 sqft large parcel",
      "Industrial zoning advantage",
      "National Highway frontage",
      "Power and water connectivity",
      "Suitable for warehousing",
    ],
    nearbyLandmarks: [
      { name: "JNPT Port", distance: "18 km", type: "other" },
      { name: "Navi Mumbai Airport", distance: "15 km", type: "airport" },
      { name: "National Highway 66", distance: "0.2 km", type: "highway" },
    ],
    investmentReasoning:
      "Industrial land near JNPT and the upcoming airport represents one of the most compelling logistics investment cases in India's western corridor. Proximity to both port and airport creates a unique multi-modal logistics advantage.",
    whyThisProperty:
      "A rare large industrial parcel with national highway frontage. Suitable for warehousing, light manufacturing, or logistics operations. Existing power and water connections reduce setup costs significantly.",
    createdAt: "2024-02-28",
    updatedAt: "2024-05-02",
  },
  {
    id: "6",
    slug: "plots-khalapur-express-highway-cluster",
    propertyCode: "PLT-KHL-003",
    title: "Express Highway Cluster – Khalapur",
    status: "available",
    featured: true,
    published: true,
    location: "Khalapur",
    village: "Pali",
    taluka: "Khalapur",
    district: "Raigad",
    coordinates: { lat: 18.8321, lng: 73.3056 },
    priceTotal: 7500000,
    pricePerSqft: 1500,
    areaSqft: 5000,
    areaGuntha: 4.59,
    areaAcre: 0.115,
    zoningType: "Residential",
    titleClarity: "clear",
    roadAccess: true,
    gallery: [
      "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
    ],
    highlights: [
      "Gated township cluster",
      "60-min drive from Mumbai",
      "Planned amenities block",
      "Clear title – ready to build",
      "Weekend home favourite zone",
    ],
    nearbyLandmarks: [
      { name: "Mumbai-Pune Expressway", distance: "1.5 km", type: "highway" },
      { name: "Khopoli", distance: "10 km", type: "market" },
      { name: "Imagica", distance: "8 km", type: "other" },
    ],
    investmentReasoning:
      "Khalapur's emerging gated township market is driven by Mumbai second-home demand. Planned township infrastructure, clear titles, and weekend drive convenience make this one of the fastest-appreciating micro-markets in Raigad.",
    whyThisProperty:
      "Part of a planned residential cluster with shared amenities. Buy a single plot or multiple adjacent plots. Ready-to-build clear title with existing road and boundary development.",
    createdAt: "2024-03-15",
    updatedAt: "2024-05-01",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Rajesh Mehta",
    location: "Mumbai",
    content:
      "Plotsify made the entire process seamless. From property selection to final registration, their team was transparent, professional, and extremely knowledgeable about the Panvel market. I invested in a 2500 sqft plot and the appreciation in 8 months has been remarkable.",
    rating: 5,
    propertyPurchased: "Premium Plot in Panvel Sector 12",
    avatar: "RM",
  },
  {
    id: "2",
    name: "Priya Sharma",
    location: "Pune",
    content:
      "We were looking for a weekend farmhouse land near Mumbai for two years. Plotsify's Khalapur listings were exactly what we needed – honest descriptions, verified titles, and the team organised a proper site visit with no pressure. Highly recommended.",
    rating: 5,
    propertyPurchased: "Weekend Farmhouse Plot in Khalapur Valley",
    avatar: "PS",
  },
  {
    id: "3",
    name: "Vikram Nair",
    location: "Dubai (NRI)",
    content:
      "As an NRI investor, trust is everything. Plotsify provided proper documentation, video tours, and their legal team assisted with the OCI card requirements. The whole deal was concluded remotely with complete peace of mind. Will definitely invest again.",
    rating: 5,
    propertyPurchased: "Residential Plot on Airport Access Road",
    avatar: "VN",
  },
  {
    id: "4",
    name: "Anita Desai",
    location: "Navi Mumbai",
    content:
      "Professional and trustworthy. I appreciated that they didn't push me into a decision. The investment reasoning section on each property listing helped me understand the 'why' behind each location. Extremely transparent about title status.",
    rating: 5,
    avatar: "AD",
  },
  {
    id: "5",
    name: "Suresh Patil",
    location: "Thane",
    content:
      "Bought a plot near the Panvel airport corridor. The site visit was well-organised and the Plotsify team knew every nearby development, road widening plan, and township approval status. This level of ground knowledge is rare.",
    rating: 5,
    propertyPurchased: "Premium Plot in Panvel Sector 12",
    avatar: "SP",
  },
];

export const LEADS: Lead[] = [
  {
    id: "1",
    name: "Aakash Verma",
    phone: "+91 98201 45123",
    email: "aakash.v@gmail.com",
    budgetRange: "50L - 1Cr",
    timeline: "3-6 months",
    purpose: "investment",
    locationPreference: "Panvel",
    interestedPropertyId: "1",
    interestedPropertyTitle: "Premium Plot in Panvel Sector 12",
    sourcePage: "Google Ads / Property Detail",
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "panvel-airport-land",
    deviceType: "mobile",
    leadScore: 85,
    leadStatus: "interested",
    assignedTo: "Rahul Sharma",
    notes: [
      {
        id: "n1",
        content: "Called twice, very interested. Has budget. Looking for investment for 3-5 year hold.",
        addedBy: "Rahul Sharma",
        addedAt: "2024-05-01",
      },
    ],
    followUps: [
      {
        id: "f1",
        scheduledFor: "2024-05-08",
        type: "call",
        notes: "Confirm site visit date",
      },
    ],
    createdAt: "2024-04-30",
    updatedAt: "2024-05-01",
  },
  {
    id: "2",
    name: "Sunita Joshi",
    phone: "+91 97123 88456",
    email: "sunita.joshi@hotmail.com",
    budgetRange: "30L - 50L",
    timeline: "1-3 months",
    purpose: "weekend-home",
    locationPreference: "Khalapur",
    interestedPropertyId: "4",
    interestedPropertyTitle: "Weekend Farmhouse Plot in Khalapur Valley",
    sourcePage: "Homepage / Organic",
    utmSource: "organic",
    utmMedium: "seo",
    deviceType: "desktop",
    leadScore: 72,
    leadStatus: "site_visit_planned",
    assignedTo: "Priya Nair",
    createdAt: "2024-04-28",
    updatedAt: "2024-05-02",
  },
  {
    id: "3",
    name: "Manish Deshmukh",
    phone: "+91 99999 11234",
    email: "m.deshmukh@company.in",
    budgetRange: "1Cr - 2Cr",
    timeline: "Immediately",
    purpose: "investment",
    locationPreference: "Panvel",
    sourcePage: "Referral",
    deviceType: "mobile",
    leadScore: 91,
    leadStatus: "negotiation",
    assignedTo: "Rahul Sharma",
    createdAt: "2024-04-25",
    updatedAt: "2024-05-04",
  },
  {
    id: "4",
    name: "Fatima Sheikh",
    phone: "+971 50 123 4567",
    email: "fatima.sheikh@dubai.ae",
    budgetRange: "1Cr+",
    timeline: "6-12 months",
    purpose: "investment",
    locationPreference: "Panvel",
    interestedPropertyId: "3",
    interestedPropertyTitle: "Residential Plot on Airport Access Road",
    sourcePage: "NRI / Meta Ads",
    utmSource: "facebook",
    utmMedium: "paid",
    utmCampaign: "nri-land-uae",
    deviceType: "mobile",
    leadScore: 78,
    leadStatus: "contacted",
    assignedTo: "Priya Nair",
    createdAt: "2024-05-01",
    updatedAt: "2024-05-02",
  },
  {
    id: "5",
    name: "Deepak Kulkarni",
    phone: "+91 88000 77654",
    email: "deepak.k@gmail.com",
    budgetRange: "Under 30L",
    timeline: "12+ months",
    purpose: "self-use",
    locationPreference: "Khalapur",
    sourcePage: "Blog / Organic",
    deviceType: "mobile",
    leadScore: 42,
    leadStatus: "new",
    createdAt: "2024-05-04",
    updatedAt: "2024-05-04",
  },
  {
    id: "6",
    name: "Kavya Reddy",
    phone: "+91 95678 23456",
    email: "kavya.r@infosys.com",
    budgetRange: "50L - 1Cr",
    timeline: "3-6 months",
    purpose: "investment",
    locationPreference: "Panvel",
    sourcePage: "Google Search",
    utmSource: "google",
    utmMedium: "organic",
    deviceType: "desktop",
    leadScore: 65,
    leadStatus: "contacted",
    assignedTo: "Rahul Sharma",
    createdAt: "2024-05-03",
    updatedAt: "2024-05-05",
  },
];

export const BLOGS: Blog[] = [
  {
    id: "1",
    title: "Why Panvel is the Next Big Land Investment Destination",
    slug: "why-panvel-land-investment-2024",
    excerpt:
      "With the Navi Mumbai International Airport nearing completion and connectivity projects transforming access, here's why Panvel sits at the epicentre of Maharashtra's next land price surge.",
    content: "",
    author: "Plotsify Research",
    category: "Investment Guide",
    tags: ["Panvel", "Land Investment", "Navi Mumbai Airport"],
    featuredImage: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800",
    published: true,
    createdAt: "2024-04-15",
  },
  {
    id: "2",
    title: "Khalapur: The Quiet Investment Playing Catch-Up",
    slug: "khalapur-land-investment-guide",
    excerpt:
      "As Mumbai's weekend home market explodes, Khalapur's proximity to the Mumbai-Pune Expressway makes it a compelling, under-the-radar option for farmhouse and investment buyers.",
    content: "",
    author: "Plotsify Research",
    category: "Location Guide",
    tags: ["Khalapur", "Weekend Home", "Farmhouse"],
    featuredImage: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800",
    published: true,
    createdAt: "2024-04-01",
  },
  {
    id: "3",
    title: "How to Read a 7/12 Extract: A Beginner's Guide",
    slug: "how-to-read-712-extract-guide",
    excerpt:
      "The 7/12 extract (Satbara Utara) is one of the most important land documents in Maharashtra. Here's what every buyer needs to understand before investing.",
    content: "",
    author: "Legal Team",
    category: "Buyer Guide",
    tags: ["Legal", "7/12", "Land Documents"],
    featuredImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800",
    published: true,
    createdAt: "2024-03-20",
  },
];

export const INFRASTRUCTURE_HIGHLIGHTS = [
  {
    id: "airport",
    title: "Navi Mumbai International Airport",
    description:
      "A major greenfield airport on ~1,160 hectares with planned capacity of 60 million passengers, set to transform Panvel's land values.",
    source: "CIDCO",
    sourceUrl: "https://cidco.maharashtra.gov.in/Page?Token=61D7D1F2278",
    icon: "plane",
    impact: "High Impact",
    location: "Panvel",
  },
  {
    id: "atalsetu",
    title: "Atal Setu (Trans Harbour Link)",
    description:
      "At 21.8 km, India's longest sea bridge improves Mumbai–Navi Mumbai connectivity, cutting travel time dramatically and boosting Panvel's accessibility.",
    source: "MMRDA",
    sourceUrl: "https://mmrda.maharashtra.gov.in/en/projects/transport/mumbai-trans-harbour-link/overview",
    icon: "bridge",
    impact: "High Impact",
    location: "Panvel",
  },
  {
    id: "missinglink",
    title: "Mumbai–Pune Expressway Missing Link",
    description:
      "Reduces a critical stretch from 19 km to 13.3 km, cutting travel time by 20–25 minutes. Khalapur becomes dramatically more accessible from Mumbai.",
    source: "MSRDC",
    sourceUrl: "https://msrdc.in/Site/Common/ProjectListDetails.aspx?ID=75&MainId=18",
    icon: "road",
    impact: "High Impact",
    location: "Khalapur",
  },
];

export const FAQS = [
  {
    id: "1",
    question: "What documents should I check before buying a plot in Panvel or Khalapur?",
    answer:
      "Key documents include the 7/12 extract (Satbara Utara), property card, mutation entries, encumbrance certificate, and NA (Non-Agricultural) order if applicable. Our team verifies all documents before listing any property.",
    category: "Legal",
  },
  {
    id: "2",
    question: "How close are your Panvel listings to the new airport?",
    answer:
      "Our Panvel listings range from 5 to 18 km from the Navi Mumbai International Airport site. Each listing clearly shows the distance to major landmarks including the airport.",
    category: "Properties",
  },
  {
    id: "3",
    question: "Can NRI buyers purchase land through Plotsify?",
    answer:
      "Yes. NRI buyers can purchase agricultural and residential land in Maharashtra with certain conditions. Our team assists with OCI card requirements, power of attorney, and remote transaction support. We have successfully completed multiple NRI transactions.",
    category: "NRI",
  },
  {
    id: "4",
    question: "What is the typical appreciation expectation in these areas?",
    answer:
      "Infrastructure corridors in Panvel have seen 15–25% annual appreciation in recent years. Khalapur has shown 10–18% appreciation, with acceleration expected post-expressway missing link completion. Past returns do not guarantee future performance.",
    category: "Investment",
  },
  {
    id: "5",
    question: "Do you organise site visits?",
    answer:
      "Yes. We organise regular weekend site visits from Mumbai and Pune pickup points. You can book a site visit through any property detail page or by calling us directly.",
    category: "Process",
  },
  {
    id: "6",
    question: "What is the process after I express interest in a property?",
    answer:
      "After enquiry, our team contacts you within 2 hours to understand your requirements. We share complete documentation, organise a site visit, and guide you through due diligence, negotiation, and registration.",
    category: "Process",
  },
];
